package com.aecg.oyunvemuzikae.ResimdenBul;

import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.media.MediaPlayer;
import android.os.Bundle;
import android.os.Handler;
import android.view.View;
import android.view.animation.Animation;
import android.view.animation.AnimationUtils;

import com.aecg.oyunvemuzikae.MainActivity;
import com.aecg.oyunvemuzikae.OyunlarMenu;
import com.aecg.oyunvemuzikae.R;
import com.aecg.oyunvemuzikae.databinding.ActivityResimdenBulPiyanoBinding;

import java.util.ArrayList;
import java.util.Random;

public class ResimdenBulPiyano extends AppCompatActivity {
    private ActivityResimdenBulPiyanoBinding binding;
    MediaPlayer soru ;
    MediaPlayer dogruses;
    Animation animation;
    Animation animationfadein;
    Animation animationmovefromleft;
    Animation animationmovefromright;
    Handler hand;
    private  View decorView;
    Runnable runab;
    MediaPlayer mediaPlayeryanliscevap;
    MediaPlayer mediaPlayerdogrucevap;
    Animation animationzoom;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        binding = ActivityResimdenBulPiyanoBinding.inflate(getLayoutInflater());
        View view = binding.getRoot();
        setContentView(view);
        decorView=getWindow().getDecorView();
        decorView.setOnSystemUiVisibilityChangeListener(new View.OnSystemUiVisibilityChangeListener() {
            @Override
            public void onSystemUiVisibilityChange(int i) {
                if(i==0){
                    decorView.setSystemUiVisibility(hideSystemBars());
                }
            }
        });
        animation = AnimationUtils.loadAnimation(getApplicationContext(),R.anim.blink_ani);
        animationzoom = AnimationUtils.loadAnimation(getApplicationContext(),R.anim.zoom_in);
        animationfadein = AnimationUtils.loadAnimation(getApplicationContext(),R.anim.fade_in);
        animationmovefromleft = AnimationUtils.loadAnimation(getApplicationContext(),R.anim.movefrom_left);
        animationmovefromright = AnimationUtils.loadAnimation(getApplicationContext(),R.anim.movefrom_right);
        binding.piycard1.startAnimation(animationmovefromleft);
        binding.piycard2.startAnimation(animationfadein);
        binding.piycard3.startAnimation(animationmovefromright);

        binding.piyanoimg1.setEnabled(false);
        binding.piyanoimg2.setEnabled(false);
        binding.piyanoimg3.setEnabled(false);
        soru = MediaPlayer.create(this, R.raw.acabapiyano);
        dogruses = MediaPlayer.create(this, R.raw.piyanoses);
        mediaPlayeryanliscevap = MediaPlayer.create(this,R.raw.yanliscevap);
        mediaPlayerdogrucevap = MediaPlayer.create(this,R.raw.tebriklerdogrucevap);
        int sorusure = soru.getDuration();
        int yanliscevapsure = mediaPlayeryanliscevap.getDuration();
        int dogrusessure = dogruses.getDuration();
        Handler handlerhizlihizli = new Handler();
        Runnable runablehizlihizli = new Runnable() {
            @Override
            public void run() {
                soru.start();
                new Handler().postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        binding.Anasayfayadonresimdenpiyano.setEnabled(true);
                        binding.Geritusuresimdenpiyano.setEnabled(true);
                        binding.piyanoimg1.setEnabled(true);
                        binding.piyanoimg2.setEnabled(true);
                        binding.piyanoimg3.setEnabled(true);
                    }
                },sorusure);
            }
        };handlerhizlihizli.postDelayed(runablehizlihizli,700);
        Random random = new Random();
        int r = random.nextInt(3);
        int r2 = random.nextInt(13);
        int r3 = random.nextInt(12);
        if(r==0){
            binding.piyanoimg1.setBackgroundResource(R.drawable.piyano);
            if(r2==0){
                binding.piyanoimg2.setBackgroundResource(R.drawable.zil);
                if(r3==0){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.bateri);
                }
                if(r3==1){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.zurna);
                }
                if(r3==2){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.keman);
                }
                if(r3==3){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.trombon);
                }
                if(r3==4){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.tef);
                }
                if(r3==5){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.baglama);
                }
                if(r3==6){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.trompetimg);
                }
                if(r3==7){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.obua);
                }
                if(r3==8){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.mentronom);
                }
                if(r3==9){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.ksilofon);
                }
                if(r3==10){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.gitar);
                }
                if(r3==11){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.flut);
                }
            }
            if(r2==1){
                binding.piyanoimg2.setBackgroundResource(R.drawable.zurna);
                if(r3==0){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.bateri);
                }
                if(r3==1){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.zil);
                }
                if(r3==2){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.keman);
                }
                if(r3==3){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.trombon);
                }
                if(r3==4){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.tef);
                }
                if(r3==5){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.baglama);
                }
                if(r3==6){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.trompetimg);
                }
                if(r3==7){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.obua);
                }
                if(r3==8){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.mentronom);
                }
                if(r3==9){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.ksilofon);
                }
                if(r3==10){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.gitar);
                }
                if(r3==11){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.flut);
                }
            }
            if(r2==2){
                binding.piyanoimg2.setBackgroundResource(R.drawable.keman);
                if(r3==0){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.bateri);
                }
                if(r3==1){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.zurna);
                }
                if(r3==2){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.zil);
                }
                if(r3==3){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.trombon);
                }
                if(r3==4){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.tef);
                }
                if(r3==5){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.baglama);
                }
                if(r3==6){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.trompetimg);
                }
                if(r3==7){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.obua);
                }
                if(r3==8){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.mentronom);
                }
                if(r3==9){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.ksilofon);
                }
                if(r3==10){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.gitar);
                }
                if(r3==11){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.flut);
                }
            }
            if(r2==3){
                binding.piyanoimg2.setBackgroundResource(R.drawable.trombon);
                if(r3==0){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.bateri);
                }
                if(r3==1){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.zurna);
                }
                if(r3==2){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.keman);
                }
                if(r3==3){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.zil);
                }
                if(r3==4){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.tef);
                }
                if(r3==5){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.baglama);
                }
                if(r3==6){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.trompetimg);
                }
                if(r3==7){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.obua);
                }
                if(r3==8){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.mentronom);
                }
                if(r3==9){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.ksilofon);
                }
                if(r3==10){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.gitar);
                }
                if(r3==11){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.flut);
                }
            }
            if(r2==4){
                binding.piyanoimg2.setBackgroundResource(R.drawable.tef);
                if(r3==0){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.bateri);
                }
                if(r3==1){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.zurna);
                }
                if(r3==2){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.keman);
                }
                if(r3==3){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.trombon);
                }
                if(r3==4){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.zil);
                }
                if(r3==5){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.baglama);
                }
                if(r3==6){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.trompetimg);
                }
                if(r3==7){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.obua);
                }
                if(r3==8){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.mentronom);
                }
                if(r3==9){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.ksilofon);
                }
                if(r3==10){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.gitar);
                }
                if(r3==11){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.flut);
                }
            }
            if(r2==5){
                binding.piyanoimg2.setBackgroundResource(R.drawable.bateri);
                if(r3==0){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.zil);
                }
                if(r3==1){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.zurna);
                }
                if(r3==2){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.keman);
                }
                if(r3==3){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.trombon);
                }
                if(r3==4){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.tef);
                }
                if(r3==5){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.baglama);
                }
                if(r3==6){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.trompetimg);
                }
                if(r3==7){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.obua);
                }
                if(r3==8){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.mentronom);
                }
                if(r3==9){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.ksilofon);
                }
                if(r3==10){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.gitar);
                }
                if(r3==11){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.flut);
                }
            }
            if(r2==6){
                binding.piyanoimg2.setBackgroundResource(R.drawable.trompetimg);
                if(r3==0){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.bateri);
                }
                if(r3==1){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.zurna);
                }
                if(r3==2){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.keman);
                }
                if(r3==3){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.trombon);
                }
                if(r3==4){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.tef);
                }
                if(r3==5){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.baglama);
                }
                if(r3==6){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.zil);
                }
                if(r3==7){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.obua);
                }
                if(r3==8){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.mentronom);
                }
                if(r3==9){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.ksilofon);
                }
                if(r3==10){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.gitar);
                }
                if(r3==11){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.flut);
                }
            }
            if(r2==7){
                binding.piyanoimg2.setBackgroundResource(R.drawable.obua);
                if(r3==0){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.bateri);
                }
                if(r3==1){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.zurna);
                }
                if(r3==2){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.keman);
                }
                if(r3==3){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.trombon);
                }
                if(r3==4){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.tef);
                }
                if(r3==5){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.baglama);
                }
                if(r3==6){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.trompetimg);
                }
                if(r3==7){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.zil);
                }
                if(r3==8){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.mentronom);
                }
                if(r3==9){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.ksilofon);
                }
                if(r3==10){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.gitar);
                }
                if(r3==11){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.flut);
                }
            }
            if(r2==8){
                binding.piyanoimg2.setBackgroundResource(R.drawable.mentronom);
                if(r3==0){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.bateri);
                }
                if(r3==1){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.zurna);
                }
                if(r3==2){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.keman);
                }
                if(r3==3){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.trombon);
                }
                if(r3==4){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.tef);
                }
                if(r3==5){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.baglama);
                }
                if(r3==6){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.trompetimg);
                }
                if(r3==7){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.obua);
                }
                if(r3==8){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.zil);
                }
                if(r3==9){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.ksilofon);
                }
                if(r3==10){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.gitar);
                }
                if(r3==11){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.flut);
                }
            }
            if(r2==9){
                binding.piyanoimg2.setBackgroundResource(R.drawable.ksilofon);
                if(r3==0){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.bateri);
                }
                if(r3==1){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.zil);
                }
                if(r3==2){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.keman);
                }
                if(r3==3){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.trombon);
                }
                if(r3==4){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.tef);
                }
                if(r3==5){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.baglama);
                }
                if(r3==6){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.trompetimg);
                }
                if(r3==7){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.obua);
                }
                if(r3==8){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.mentronom);
                }
                if(r3==9){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.zurna);
                }
                if(r3==10){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.gitar);
                }
                if(r3==11){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.flut);
                }
            }
            if(r2==10){
                binding.piyanoimg2.setBackgroundResource(R.drawable.gitar);
                if(r3==0){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.bateri);
                }
                if(r3==1){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.zil);
                }
                if(r3==2){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.keman);
                }
                if(r3==3){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.trombon);
                }
                if(r3==4){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.tef);
                }
                if(r3==5){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.baglama);
                }
                if(r3==6){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.trompetimg);
                }
                if(r3==7){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.obua);
                }
                if(r3==8){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.mentronom);
                }
                if(r3==9){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.ksilofon);
                }
                if(r3==10){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.zurna);
                }
                if(r3==11){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.flut);
                }
            }
            if(r2==11){
                binding.piyanoimg2.setBackgroundResource(R.drawable.flut);
                if(r3==0){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.bateri);
                }
                if(r3==1){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.zil);
                }
                if(r3==2){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.keman);
                }
                if(r3==3){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.trombon);
                }
                if(r3==4){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.tef);
                }
                if(r3==5){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.baglama);
                }
                if(r3==6){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.trompetimg);
                }
                if(r3==7){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.obua);
                }
                if(r3==8){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.mentronom);
                }
                if(r3==9){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.ksilofon);
                }
                if(r3==10){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.gitar);
                }
                if(r3==11){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.zurna);
                }
            }
            if(r2==12){
                binding.piyanoimg2.setBackgroundResource(R.drawable.baglama);
                if(r3==0){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.bateri);
                }
                if(r3==1){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.zil);
                }
                if(r3==2){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.keman);
                }
                if(r3==3){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.trombon);
                }
                if(r3==4){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.tef);
                }
                if(r3==5){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.zurna);
                }
                if(r3==6){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.trompetimg);
                }
                if(r3==7){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.obua);
                }
                if(r3==8){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.mentronom);
                }
                if(r3==9){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.ksilofon);
                }
                if(r3==10){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.gitar);
                }
                if(r3==11){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.flut);
                }
            }
        }
        if(r==1){
            binding.piyanoimg2.setBackgroundResource(R.drawable.piyano);
            if(r2==0){
                binding.piyanoimg1.setBackgroundResource(R.drawable.zil);
                if(r3==0){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.bateri);
                }
                if(r3==1){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.zurna);
                }
                if(r3==2){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.keman);
                }
                if(r3==3){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.trombon);
                }
                if(r3==4){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.tef);
                }
                if(r3==5){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.baglama);
                }
                if(r3==6){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.trompetimg);
                }
                if(r3==7){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.obua);
                }
                if(r3==8){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.mentronom);
                }
                if(r3==9){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.ksilofon);
                }
                if(r3==10){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.gitar);
                }
                if(r3==11){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.flut);
                }
            }
            if(r2==1){
                binding.piyanoimg1.setBackgroundResource(R.drawable.zurna);
                if(r3==0){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.bateri);
                }
                if(r3==1){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.zil);
                }
                if(r3==2){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.keman);
                }
                if(r3==3){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.trombon);
                }
                if(r3==4){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.tef);
                }
                if(r3==5){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.baglama);
                }
                if(r3==6){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.trompetimg);
                }
                if(r3==7){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.obua);
                }
                if(r3==8){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.mentronom);
                }
                if(r3==9){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.ksilofon);
                }
                if(r3==10){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.gitar);
                }
                if(r3==11){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.flut);
                }
            }
            if(r2==2){
                binding.piyanoimg1.setBackgroundResource(R.drawable.keman);
                if(r3==0){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.bateri);
                }
                if(r3==1){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.zurna);
                }
                if(r3==2){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.zil);
                }
                if(r3==3){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.trombon);
                }
                if(r3==4){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.tef);
                }
                if(r3==5){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.baglama);
                }
                if(r3==6){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.trompetimg);
                }
                if(r3==7){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.obua);
                }
                if(r3==8){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.mentronom);
                }
                if(r3==9){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.ksilofon);
                }
                if(r3==10){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.gitar);
                }
                if(r3==11){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.flut);
                }
            }
            if(r2==3){
                binding.piyanoimg1.setBackgroundResource(R.drawable.trombon);
                if(r3==0){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.bateri);
                }
                if(r3==1){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.zurna);
                }
                if(r3==2){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.keman);
                }
                if(r3==3){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.zil);
                }
                if(r3==4){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.tef);
                }
                if(r3==5){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.baglama);
                }
                if(r3==6){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.trompetimg);
                }
                if(r3==7){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.obua);
                }
                if(r3==8){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.mentronom);
                }
                if(r3==9){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.ksilofon);
                }
                if(r3==10){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.gitar);
                }
                if(r3==11){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.flut);
                }
            }
            if(r2==4){
                binding.piyanoimg1.setBackgroundResource(R.drawable.tef);
                if(r3==0){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.bateri);
                }
                if(r3==1){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.zurna);
                }
                if(r3==2){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.keman);
                }
                if(r3==3){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.trombon);
                }
                if(r3==4){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.zil);
                }
                if(r3==5){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.baglama);
                }
                if(r3==6){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.trompetimg);
                }
                if(r3==7){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.obua);
                }
                if(r3==8){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.mentronom);
                }
                if(r3==9){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.ksilofon);
                }
                if(r3==10){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.gitar);
                }
                if(r3==11){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.flut);
                }
            }
            if(r2==5){
                binding.piyanoimg1.setBackgroundResource(R.drawable.bateri);
                if(r3==0){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.zil);
                }
                if(r3==1){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.zurna);
                }
                if(r3==2){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.keman);
                }
                if(r3==3){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.trombon);
                }
                if(r3==4){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.tef);
                }
                if(r3==5){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.baglama);
                }
                if(r3==6){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.trompetimg);
                }
                if(r3==7){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.obua);
                }
                if(r3==8){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.mentronom);
                }
                if(r3==9){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.ksilofon);
                }
                if(r3==10){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.gitar);
                }
                if(r3==11){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.flut);
                }
            }
            if(r2==6){
                binding.piyanoimg1.setBackgroundResource(R.drawable.trompetimg);
                if(r3==0){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.bateri);
                }
                if(r3==1){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.zurna);
                }
                if(r3==2){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.keman);
                }
                if(r3==3){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.trombon);
                }
                if(r3==4){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.tef);
                }
                if(r3==5){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.baglama);
                }
                if(r3==6){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.zil);
                }
                if(r3==7){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.obua);
                }
                if(r3==8){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.mentronom);
                }
                if(r3==9){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.ksilofon);
                }
                if(r3==10){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.gitar);
                }
                if(r3==11){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.flut);
                }
            }
            if(r2==7){
                binding.piyanoimg1.setBackgroundResource(R.drawable.obua);
                if(r3==0){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.bateri);
                }
                if(r3==1){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.zurna);
                }
                if(r3==2){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.keman);
                }
                if(r3==3){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.trombon);
                }
                if(r3==4){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.tef);
                }
                if(r3==5){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.baglama);
                }
                if(r3==6){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.trompetimg);
                }
                if(r3==7){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.zil);
                }
                if(r3==8){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.mentronom);
                }
                if(r3==9){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.ksilofon);
                }
                if(r3==10){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.gitar);
                }
                if(r3==11){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.flut);
                }
            }
            if(r2==8){
                binding.piyanoimg1.setBackgroundResource(R.drawable.mentronom);
                if(r3==0){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.bateri);
                }
                if(r3==1){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.zurna);
                }
                if(r3==2){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.keman);
                }
                if(r3==3){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.trombon);
                }
                if(r3==4){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.tef);
                }
                if(r3==5){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.baglama);
                }
                if(r3==6){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.trompetimg);
                }
                if(r3==7){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.obua);
                }
                if(r3==8){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.zil);
                }
                if(r3==9){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.ksilofon);
                }
                if(r3==10){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.gitar);
                }
                if(r3==11){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.flut);
                }
            }
            if(r2==9){
                binding.piyanoimg1.setBackgroundResource(R.drawable.ksilofon);
                if(r3==0){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.bateri);
                }
                if(r3==1){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.zil);
                }
                if(r3==2){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.keman);
                }
                if(r3==3){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.trombon);
                }
                if(r3==4){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.tef);
                }
                if(r3==5){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.baglama);
                }
                if(r3==6){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.trompetimg);
                }
                if(r3==7){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.obua);
                }
                if(r3==8){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.mentronom);
                }
                if(r3==9){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.zurna);
                }
                if(r3==10){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.gitar);
                }
                if(r3==11){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.flut);
                }
            }
            if(r2==10){
                binding.piyanoimg1.setBackgroundResource(R.drawable.gitar);
                if(r3==0){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.bateri);
                }
                if(r3==1){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.zil);
                }
                if(r3==2){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.keman);
                }
                if(r3==3){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.trombon);
                }
                if(r3==4){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.tef);
                }
                if(r3==5){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.baglama);
                }
                if(r3==6){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.trompetimg);
                }
                if(r3==7){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.obua);
                }
                if(r3==8){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.mentronom);
                }
                if(r3==9){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.ksilofon);
                }
                if(r3==10){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.zurna);
                }
                if(r3==11){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.flut);
                }
            }
            if(r2==11){
                binding.piyanoimg1.setBackgroundResource(R.drawable.flut);
                if(r3==0){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.bateri);
                }
                if(r3==1){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.zil);
                }
                if(r3==2){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.keman);
                }
                if(r3==3){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.trombon);
                }
                if(r3==4){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.tef);
                }
                if(r3==5){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.baglama);
                }
                if(r3==6){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.trompetimg);
                }
                if(r3==7){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.obua);
                }
                if(r3==8){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.mentronom);
                }
                if(r3==9){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.ksilofon);
                }
                if(r3==10){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.gitar);
                }
                if(r3==11){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.zurna);
                }
            }
            if(r2==12){
                binding.piyanoimg1.setBackgroundResource(R.drawable.baglama);
                if(r3==0){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.bateri);
                }
                if(r3==1){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.zil);
                }
                if(r3==2){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.keman);
                }
                if(r3==3){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.trombon);
                }
                if(r3==4){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.tef);
                }
                if(r3==5){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.zurna);
                }
                if(r3==6){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.trompetimg);
                }
                if(r3==7){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.obua);
                }
                if(r3==8){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.mentronom);
                }
                if(r3==9){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.ksilofon);
                }
                if(r3==10){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.gitar);
                }
                if(r3==11){
                    binding.piyanoimg3.setBackgroundResource(R.drawable.flut);
                }
            }
        }
        if(r==2){
            binding.piyanoimg3.setBackgroundResource(R.drawable.piyano);
            if(r2==0){
                binding.piyanoimg2.setBackgroundResource(R.drawable.zil);
                if(r3==0){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.bateri);
                }
                if(r3==1){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.zurna);
                }
                if(r3==2){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.keman);
                }
                if(r3==3){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.trombon);
                }
                if(r3==4){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.tef);
                }
                if(r3==5){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.baglama);
                }
                if(r3==6){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.trompetimg);
                }
                if(r3==7){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.obua);
                }
                if(r3==8){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.mentronom);
                }
                if(r3==9){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.ksilofon);
                }
                if(r3==10){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.gitar);
                }
                if(r3==11){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.flut);
                }
            }
            if(r2==1){
                binding.piyanoimg2.setBackgroundResource(R.drawable.zurna);
                if(r3==0){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.bateri);
                }
                if(r3==1){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.zil);
                }
                if(r3==2){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.keman);
                }
                if(r3==3){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.trombon);
                }
                if(r3==4){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.tef);
                }
                if(r3==5){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.baglama);
                }
                if(r3==6){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.trompetimg);
                }
                if(r3==7){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.obua);
                }
                if(r3==8){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.mentronom);
                }
                if(r3==9){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.ksilofon);
                }
                if(r3==10){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.gitar);
                }
                if(r3==11){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.flut);
                }
            }
            if(r2==2){
                binding.piyanoimg2.setBackgroundResource(R.drawable.keman);
                if(r3==0){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.bateri);
                }
                if(r3==1){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.zurna);
                }
                if(r3==2){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.zil);
                }
                if(r3==3){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.trombon);
                }
                if(r3==4){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.tef);
                }
                if(r3==5){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.baglama);
                }
                if(r3==6){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.trompetimg);
                }
                if(r3==7){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.obua);
                }
                if(r3==8){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.mentronom);
                }
                if(r3==9){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.ksilofon);
                }
                if(r3==10){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.gitar);
                }
                if(r3==11){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.flut);
                }
            }
            if(r2==3){
                binding.piyanoimg2.setBackgroundResource(R.drawable.trombon);
                if(r3==0){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.bateri);
                }
                if(r3==1){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.zurna);
                }
                if(r3==2){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.keman);
                }
                if(r3==3){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.zil);
                }
                if(r3==4){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.tef);
                }
                if(r3==5){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.baglama);
                }
                if(r3==6){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.trompetimg);
                }
                if(r3==7){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.obua);
                }
                if(r3==8){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.mentronom);
                }
                if(r3==9){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.ksilofon);
                }
                if(r3==10){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.gitar);
                }
                if(r3==11){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.flut);
                }
            }
            if(r2==4){
                binding.piyanoimg2.setBackgroundResource(R.drawable.tef);
                if(r3==0){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.bateri);
                }
                if(r3==1){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.zurna);
                }
                if(r3==2){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.keman);
                }
                if(r3==3){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.trombon);
                }
                if(r3==4){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.zil);
                }
                if(r3==5){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.baglama);
                }
                if(r3==6){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.trompetimg);
                }
                if(r3==7){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.obua);
                }
                if(r3==8){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.mentronom);
                }
                if(r3==9){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.ksilofon);
                }
                if(r3==10){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.gitar);
                }
                if(r3==11){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.flut);
                }
            }
            if(r2==5){
                binding.piyanoimg2.setBackgroundResource(R.drawable.bateri);
                if(r3==0){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.zil);
                }
                if(r3==1){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.zurna);
                }
                if(r3==2){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.keman);
                }
                if(r3==3){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.trombon);
                }
                if(r3==4){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.tef);
                }
                if(r3==5){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.baglama);
                }
                if(r3==6){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.trompetimg);
                }
                if(r3==7){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.obua);
                }
                if(r3==8){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.mentronom);
                }
                if(r3==9){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.ksilofon);
                }
                if(r3==10){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.gitar);
                }
                if(r3==11){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.flut);
                }
            }
            if(r2==6){
                binding.piyanoimg2.setBackgroundResource(R.drawable.trompetimg);
                if(r3==0){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.bateri);
                }
                if(r3==1){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.zurna);
                }
                if(r3==2){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.keman);
                }
                if(r3==3){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.trombon);
                }
                if(r3==4){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.tef);
                }
                if(r3==5){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.baglama);
                }
                if(r3==6){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.zil);
                }
                if(r3==7){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.obua);
                }
                if(r3==8){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.mentronom);
                }
                if(r3==9){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.ksilofon);
                }
                if(r3==10){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.gitar);
                }
                if(r3==11){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.flut);
                }
            }
            if(r2==7){
                binding.piyanoimg2.setBackgroundResource(R.drawable.obua);
                if(r3==0){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.bateri);
                }
                if(r3==1){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.zurna);
                }
                if(r3==2){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.keman);
                }
                if(r3==3){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.trombon);
                }
                if(r3==4){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.tef);
                }
                if(r3==5){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.baglama);
                }
                if(r3==6){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.trompetimg);
                }
                if(r3==7){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.zil);
                }
                if(r3==8){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.mentronom);
                }
                if(r3==9){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.ksilofon);
                }
                if(r3==10){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.gitar);
                }
                if(r3==11){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.flut);
                }
            }
            if(r2==8){
                binding.piyanoimg2.setBackgroundResource(R.drawable.mentronom);
                if(r3==0){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.bateri);
                }
                if(r3==1){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.zurna);
                }
                if(r3==2){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.keman);
                }
                if(r3==3){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.trombon);
                }
                if(r3==4){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.tef);
                }
                if(r3==5){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.baglama);
                }
                if(r3==6){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.trompetimg);
                }
                if(r3==7){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.obua);
                }
                if(r3==8){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.zil);
                }
                if(r3==9){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.ksilofon);
                }
                if(r3==10){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.gitar);
                }
                if(r3==11){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.flut);
                }
            }
            if(r2==9){
                binding.piyanoimg2.setBackgroundResource(R.drawable.ksilofon);
                if(r3==0){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.bateri);
                }
                if(r3==1){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.zil);
                }
                if(r3==2){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.keman);
                }
                if(r3==3){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.trombon);
                }
                if(r3==4){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.tef);
                }
                if(r3==5){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.baglama);
                }
                if(r3==6){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.trompetimg);
                }
                if(r3==7){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.obua);
                }
                if(r3==8){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.mentronom);
                }
                if(r3==9){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.zurna);
                }
                if(r3==10){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.gitar);
                }
                if(r3==11){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.flut);
                }
            }
            if(r2==10){
                binding.piyanoimg2.setBackgroundResource(R.drawable.gitar);
                if(r3==0){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.bateri);
                }
                if(r3==1){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.zil);
                }
                if(r3==2){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.keman);
                }
                if(r3==3){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.trombon);
                }
                if(r3==4){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.tef);
                }
                if(r3==5){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.baglama);
                }
                if(r3==6){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.trompetimg);
                }
                if(r3==7){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.obua);
                }
                if(r3==8){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.mentronom);
                }
                if(r3==9){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.ksilofon);
                }
                if(r3==10){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.zurna);
                }
                if(r3==11){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.flut);
                }
            }
            if(r2==11){
                binding.piyanoimg2.setBackgroundResource(R.drawable.flut);
                if(r3==0){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.bateri);
                }
                if(r3==1){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.zil);
                }
                if(r3==2){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.keman);
                }
                if(r3==3){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.trombon);
                }
                if(r3==4){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.tef);
                }
                if(r3==5){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.baglama);
                }
                if(r3==6){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.trompetimg);
                }
                if(r3==7){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.obua);
                }
                if(r3==8){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.mentronom);
                }
                if(r3==9){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.ksilofon);
                }
                if(r3==10){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.gitar);
                }
                if(r3==11){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.zurna);
                }
            }
            if(r2==12){
                binding.piyanoimg2.setBackgroundResource(R.drawable.baglama);
                if(r3==0){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.bateri);
                }
                if(r3==1){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.zil);
                }
                if(r3==2){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.keman);
                }
                if(r3==3){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.trombon);
                }
                if(r3==4){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.tef);
                }
                if(r3==5){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.zurna);
                }
                if(r3==6){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.trompetimg);
                }
                if(r3==7){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.obua);
                }
                if(r3==8){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.mentronom);
                }
                if(r3==9){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.ksilofon);
                }
                if(r3==10){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.gitar);
                }
                if(r3==11){
                    binding.piyanoimg1.setBackgroundResource(R.drawable.flut);
                }
            }
        }
        binding.Anasayfayadonresimdenpiyano.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                if(hand!=null){
                    hand.removeCallbacks(runab);
                }

                seskes();
                Intent intent = new Intent(ResimdenBulPiyano.this, MainActivity.class);
                intent.addFlags(Intent.FLAG_ACTIVITY_NO_HISTORY);
                startActivity(intent);
                finish();
            }
        });
        binding.Geritusuresimdenpiyano.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                if(hand!=null){
                    hand.removeCallbacks(runab);
                }

                seskes();
                Intent intent = new Intent(ResimdenBulPiyano.this, OyunlarMenu.class);
                intent.addFlags(Intent.FLAG_ACTIVITY_NO_HISTORY);
                startActivity(intent);
                finish();
            }
        });

        binding.piyanoimg1.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                if(r==0){
                    binding.piycard1.setBackgroundResource(R.drawable.border);
                    binding.piycard1.startAnimation(animationzoom);
                    binding.piyanoimg1.setClickable(false);
                    binding.piyanoimg2.setClickable(false);
                    binding.piyanoimg3.setClickable(false);
                    mediaPlayerdogrucevap.start();
                    mediaPlayerdogrucevap.setOnCompletionListener(new MediaPlayer.OnCompletionListener() {
                        @Override
                        public void onCompletion(MediaPlayer mediaPlayer) {
                            dogruses.start();
                            binding.imageView.setVisibility(View.VISIBLE);
                            binding.imageView.startAnimation(animation);
                            dogruses.setOnCompletionListener(new MediaPlayer.OnCompletionListener() {
                                @Override
                                public void onCompletion(MediaPlayer mediaPlayer) {
                                    randomact();
                                }
                            });
                        }
                    });

                    binding.imageView.setOnClickListener(new View.OnClickListener() {
                        @Override
                        public void onClick(View view) {
                            randomact();
                        }
                    });
                }
                if(r==1){
                    binding.piycard1.setBackgroundResource(R.drawable.border_red);

                }
                if(r==2){
                    binding.piycard1.setBackgroundResource(R.drawable.border_red);

                }
            }
        });
        binding.piyanoimg2.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                if(r==0){
                    binding.piycard2.setBackgroundResource(R.drawable.border_red);

                }
                if(r==1){
                    binding.piycard2.setBackgroundResource(R.drawable.border);
                    binding.piycard2.startAnimation(animationzoom);

                    binding.piyanoimg1.setClickable(false);
                    binding.piyanoimg2.setClickable(false);
                    binding.piyanoimg3.setClickable(false);
                    mediaPlayerdogrucevap.start();
                    mediaPlayerdogrucevap.setOnCompletionListener(new MediaPlayer.OnCompletionListener() {
                        @Override
                        public void onCompletion(MediaPlayer mediaPlayer) {
                            dogruses.start();
                            binding.imageView.setVisibility(View.VISIBLE);
                            binding.imageView.startAnimation(animation);
                            dogruses.setOnCompletionListener(new MediaPlayer.OnCompletionListener() {
                                @Override
                                public void onCompletion(MediaPlayer mediaPlayer) {
                                    randomact();
                                }
                            });
                        }
                    });

                    binding.imageView.setOnClickListener(new View.OnClickListener() {
                        @Override
                        public void onClick(View view) {

                            randomact();
                        }
                    });
                }
                if(r==2){
                    binding.piycard2.setBackgroundResource(R.drawable.border_red);

                }
            }
        });
        binding.piyanoimg3.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                if(r==0){
                    binding.piycard3.setBackgroundResource(R.drawable.border_red);

                }
                if(r==1){
                    binding.piycard3.setBackgroundResource(R.drawable.border_red);

                }
                if(r==2){
                    binding.piycard3.setBackgroundResource(R.drawable.border);
                    binding.piycard3.startAnimation(animationzoom);
                    binding.piyanoimg1.setClickable(false);
                    binding.piyanoimg2.setClickable(false);
                    binding.piyanoimg3.setClickable(false);
                    mediaPlayerdogrucevap.start();
                    mediaPlayerdogrucevap.setOnCompletionListener(new MediaPlayer.OnCompletionListener() {
                        @Override
                        public void onCompletion(MediaPlayer mediaPlayer) {
                            dogruses.start();
                            binding.imageView.setVisibility(View.VISIBLE);
                            binding.imageView.startAnimation(animation);
                            dogruses.setOnCompletionListener(new MediaPlayer.OnCompletionListener() {
                                @Override
                                public void onCompletion(MediaPlayer mediaPlayer) {
                                    randomact();
                                }
                            });
                        }
                    });

                    binding.imageView.setOnClickListener(new View.OnClickListener() {
                        @Override
                        public void onClick(View view) {

                            randomact();
                        }
                    });
                }
            }
        });
    }
    public void seskes() {
        if(soru!=null){
            soru.stop();
            soru.release();
            soru = null;
        }
        if(dogruses!=null){
            dogruses.stop();
            dogruses.release();
            dogruses = null;
        }
        if(mediaPlayeryanliscevap!=null){
            mediaPlayeryanliscevap.stop();
            mediaPlayeryanliscevap.release();
            mediaPlayeryanliscevap = null;
        }
        if(mediaPlayerdogrucevap!=null){
            mediaPlayerdogrucevap.stop();
            mediaPlayerdogrucevap.release();
            mediaPlayerdogrucevap = null;
        }
    }
    public void randomact(){
        seskes();
        ArrayList<Class> activitylist = new ArrayList<>();
        Bundle extras = getIntent().getExtras();
        activitylist = (ArrayList<Class>) extras.get("ACTIVITY_LIST");

        Random generator = new Random();
        int number = generator.nextInt(activitylist.size());
        if(number ==0){
            Intent intent = new Intent(getApplicationContext(), activitylist.get(0));
            activitylist.remove(0);
            if(activitylist.size()==0){
                activitylist.add(ResimdenBulBaglama.class);
                activitylist.add(ResimdenBulBateri.class);
                activitylist.add(ResimdenBulDavul.class);
                activitylist.add(ResimdenBulDef.class);
                activitylist.add(ResimdenBulFlut.class);
                activitylist.add(ResimdenBulKeman.class);
                activitylist.add(ResimdenBulKsilafon.class);
                activitylist.add(ResimdenBulMetronom.class);
                activitylist.add(ResimdenBulObua.class);
                activitylist.add(ResimdenBulPiyano.class);
                activitylist.add(ResimdenBulTrombon.class);
                activitylist.add(ResimdenBulTrompet.class);
                activitylist.add(ResimdenBulZil.class);
                activitylist.add(ResimdenBulZurna.class);
                activitylist.add(ResimdenBulGitar.class);
                activitylist.add(ResimdenBulUd.class);
                activitylist.add(ResimdenBulKanun.class);
            }
            intent.putExtra("ACTIVITY_LIST", activitylist);
            intent.addFlags(Intent.FLAG_ACTIVITY_NO_HISTORY);
            startActivity(intent);
            finish();
        }
        if(number ==1){
            Intent intent = new Intent(getApplicationContext(), activitylist.get(1));
            activitylist.remove(1);
            if(activitylist.size()==0){
                activitylist.add(ResimdenBulBaglama.class);
                activitylist.add(ResimdenBulBateri.class);
                activitylist.add(ResimdenBulDavul.class);
                activitylist.add(ResimdenBulDef.class);
                activitylist.add(ResimdenBulFlut.class);
                activitylist.add(ResimdenBulKeman.class);
                activitylist.add(ResimdenBulKsilafon.class);
                activitylist.add(ResimdenBulMetronom.class);
                activitylist.add(ResimdenBulObua.class);
                activitylist.add(ResimdenBulPiyano.class);
                activitylist.add(ResimdenBulTrombon.class);
                activitylist.add(ResimdenBulTrompet.class);
                activitylist.add(ResimdenBulZil.class);
                activitylist.add(ResimdenBulZurna.class);
                activitylist.add(ResimdenBulGitar.class);
                activitylist.add(ResimdenBulUd.class);
                activitylist.add(ResimdenBulKanun.class);

            }
            intent.putExtra("ACTIVITY_LIST", activitylist);
            intent.addFlags(Intent.FLAG_ACTIVITY_NO_HISTORY);
            startActivity(intent);
            finish();
        }
        if(number ==2){
            Intent intent = new Intent(getApplicationContext(), activitylist.get(2));
            activitylist.remove(2);
            if(activitylist.size()==0){
                activitylist.add(ResimdenBulBaglama.class);
                activitylist.add(ResimdenBulBateri.class);
                activitylist.add(ResimdenBulDavul.class);
                activitylist.add(ResimdenBulDef.class);
                activitylist.add(ResimdenBulFlut.class);
                activitylist.add(ResimdenBulKeman.class);
                activitylist.add(ResimdenBulKsilafon.class);
                activitylist.add(ResimdenBulMetronom.class);
                activitylist.add(ResimdenBulObua.class);
                activitylist.add(ResimdenBulPiyano.class);
                activitylist.add(ResimdenBulTrombon.class);
                activitylist.add(ResimdenBulTrompet.class);
                activitylist.add(ResimdenBulZil.class);
                activitylist.add(ResimdenBulZurna.class);
                activitylist.add(ResimdenBulGitar.class);
                activitylist.add(ResimdenBulUd.class);
                activitylist.add(ResimdenBulKanun.class);

            }
            intent.putExtra("ACTIVITY_LIST", activitylist);
            intent.addFlags(Intent.FLAG_ACTIVITY_NO_HISTORY);
            startActivity(intent);
            finish();
        }
        if(number ==3){
            Intent intent = new Intent(getApplicationContext(), activitylist.get(3));
            activitylist.remove(3);
            if(activitylist.size()==0){
                activitylist.add(ResimdenBulBaglama.class);
                activitylist.add(ResimdenBulBateri.class);
                activitylist.add(ResimdenBulDavul.class);
                activitylist.add(ResimdenBulDef.class);
                activitylist.add(ResimdenBulFlut.class);
                activitylist.add(ResimdenBulKeman.class);
                activitylist.add(ResimdenBulKsilafon.class);
                activitylist.add(ResimdenBulMetronom.class);
                activitylist.add(ResimdenBulObua.class);
                activitylist.add(ResimdenBulPiyano.class);
                activitylist.add(ResimdenBulGitar.class);
                activitylist.add(ResimdenBulTrombon.class);
                activitylist.add(ResimdenBulTrompet.class);
                activitylist.add(ResimdenBulZil.class);
                activitylist.add(ResimdenBulZurna.class);
                activitylist.add(ResimdenBulUd.class);
                activitylist.add(ResimdenBulKanun.class);

            }
            intent.putExtra("ACTIVITY_LIST", activitylist);
            intent.addFlags(Intent.FLAG_ACTIVITY_NO_HISTORY);
            startActivity(intent);
            finish();
        }
        if(number ==4){
            Intent intent = new Intent(getApplicationContext(), activitylist.get(4));
            activitylist.remove(4);
            if(activitylist.size()==0){
                activitylist.add(ResimdenBulBaglama.class);
                activitylist.add(ResimdenBulBateri.class);
                activitylist.add(ResimdenBulDavul.class);
                activitylist.add(ResimdenBulDef.class);
                activitylist.add(ResimdenBulFlut.class);
                activitylist.add(ResimdenBulKeman.class);
                activitylist.add(ResimdenBulKsilafon.class);
                activitylist.add(ResimdenBulMetronom.class);
                activitylist.add(ResimdenBulObua.class);
                activitylist.add(ResimdenBulPiyano.class);
                activitylist.add(ResimdenBulTrombon.class);
                activitylist.add(ResimdenBulTrompet.class);
                activitylist.add(ResimdenBulGitar.class);
                activitylist.add(ResimdenBulZil.class);
                activitylist.add(ResimdenBulZurna.class);
                activitylist.add(ResimdenBulUd.class);
                activitylist.add(ResimdenBulKanun.class);

            }
            intent.putExtra("ACTIVITY_LIST", activitylist);
            intent.addFlags(Intent.FLAG_ACTIVITY_NO_HISTORY);
            startActivity(intent);
            finish();
        }
        if(number ==5){
            Intent intent = new Intent(getApplicationContext(), activitylist.get(5));
            activitylist.remove(5);
            if(activitylist.size()==0){
                activitylist.add(ResimdenBulBaglama.class);
                activitylist.add(ResimdenBulBateri.class);
                activitylist.add(ResimdenBulDavul.class);
                activitylist.add(ResimdenBulDef.class);
                activitylist.add(ResimdenBulFlut.class);
                activitylist.add(ResimdenBulKeman.class);
                activitylist.add(ResimdenBulKsilafon.class);
                activitylist.add(ResimdenBulMetronom.class);
                activitylist.add(ResimdenBulObua.class);
                activitylist.add(ResimdenBulPiyano.class);
                activitylist.add(ResimdenBulGitar.class);
                activitylist.add(ResimdenBulTrombon.class);
                activitylist.add(ResimdenBulTrompet.class);
                activitylist.add(ResimdenBulZil.class);
                activitylist.add(ResimdenBulZurna.class);
                activitylist.add(ResimdenBulUd.class);
                activitylist.add(ResimdenBulKanun.class);

            }
            intent.putExtra("ACTIVITY_LIST", activitylist);
            intent.addFlags(Intent.FLAG_ACTIVITY_NO_HISTORY);
            startActivity(intent);
            finish();
        }
        if(number ==6){
            Intent intent = new Intent(getApplicationContext(), activitylist.get(6));
            activitylist.remove(6);
            if(activitylist.size()==0){
                activitylist.add(ResimdenBulBaglama.class);
                activitylist.add(ResimdenBulBateri.class);
                activitylist.add(ResimdenBulDavul.class);
                activitylist.add(ResimdenBulDef.class);
                activitylist.add(ResimdenBulFlut.class);
                activitylist.add(ResimdenBulKeman.class);
                activitylist.add(ResimdenBulKsilafon.class);
                activitylist.add(ResimdenBulGitar.class);
                activitylist.add(ResimdenBulMetronom.class);
                activitylist.add(ResimdenBulObua.class);
                activitylist.add(ResimdenBulPiyano.class);
                activitylist.add(ResimdenBulTrombon.class);
                activitylist.add(ResimdenBulTrompet.class);
                activitylist.add(ResimdenBulZil.class);
                activitylist.add(ResimdenBulZurna.class);
                activitylist.add(ResimdenBulUd.class);
                activitylist.add(ResimdenBulKanun.class);

            }
            intent.putExtra("ACTIVITY_LIST", activitylist);
            intent.addFlags(Intent.FLAG_ACTIVITY_NO_HISTORY);
            startActivity(intent);
            finish();
        }
        if(number ==7){
            Intent intent = new Intent(getApplicationContext(), activitylist.get(7));
            activitylist.remove(7);
            if(activitylist.size()==0){
                activitylist.add(ResimdenBulBaglama.class);
                activitylist.add(ResimdenBulBateri.class);
                activitylist.add(ResimdenBulDavul.class);
                activitylist.add(ResimdenBulDef.class);
                activitylist.add(ResimdenBulFlut.class);
                activitylist.add(ResimdenBulKeman.class);
                activitylist.add(ResimdenBulKsilafon.class);
                activitylist.add(ResimdenBulGitar.class);
                activitylist.add(ResimdenBulMetronom.class);
                activitylist.add(ResimdenBulObua.class);
                activitylist.add(ResimdenBulPiyano.class);
                activitylist.add(ResimdenBulTrombon.class);
                activitylist.add(ResimdenBulTrompet.class);
                activitylist.add(ResimdenBulZil.class);
                activitylist.add(ResimdenBulZurna.class);
                activitylist.add(ResimdenBulUd.class);
                activitylist.add(ResimdenBulKanun.class);

            }
            intent.putExtra("ACTIVITY_LIST", activitylist);
            intent.addFlags(Intent.FLAG_ACTIVITY_NO_HISTORY);
            startActivity(intent);
            finish();
        }
        if(number ==8){
            Intent intent = new Intent(getApplicationContext(), activitylist.get(8));
            activitylist.remove(8);
            if(activitylist.size()==0){
                activitylist.add(ResimdenBulBaglama.class);
                activitylist.add(ResimdenBulBateri.class);
                activitylist.add(ResimdenBulDavul.class);
                activitylist.add(ResimdenBulDef.class);
                activitylist.add(ResimdenBulFlut.class);
                activitylist.add(ResimdenBulKeman.class);
                activitylist.add(ResimdenBulKsilafon.class);
                activitylist.add(ResimdenBulGitar.class);
                activitylist.add(ResimdenBulMetronom.class);
                activitylist.add(ResimdenBulObua.class);
                activitylist.add(ResimdenBulPiyano.class);
                activitylist.add(ResimdenBulTrombon.class);
                activitylist.add(ResimdenBulTrompet.class);
                activitylist.add(ResimdenBulZil.class);
                activitylist.add(ResimdenBulZurna.class);
                activitylist.add(ResimdenBulUd.class);
                activitylist.add(ResimdenBulKanun.class);

            }
            intent.putExtra("ACTIVITY_LIST", activitylist);
            intent.addFlags(Intent.FLAG_ACTIVITY_NO_HISTORY);
            startActivity(intent);
            finish();
        }
        if(number ==9){
            Intent intent = new Intent(getApplicationContext(), activitylist.get(9));
            activitylist.remove(9);
            if(activitylist.size()==0){
                activitylist.add(ResimdenBulBaglama.class);
                activitylist.add(ResimdenBulBateri.class);
                activitylist.add(ResimdenBulDavul.class);
                activitylist.add(ResimdenBulDef.class);
                activitylist.add(ResimdenBulFlut.class);
                activitylist.add(ResimdenBulKeman.class);
                activitylist.add(ResimdenBulKsilafon.class);
                activitylist.add(ResimdenBulGitar.class);
                activitylist.add(ResimdenBulMetronom.class);
                activitylist.add(ResimdenBulObua.class);
                activitylist.add(ResimdenBulPiyano.class);
                activitylist.add(ResimdenBulTrombon.class);
                activitylist.add(ResimdenBulTrompet.class);
                activitylist.add(ResimdenBulZil.class);
                activitylist.add(ResimdenBulZurna.class);
                activitylist.add(ResimdenBulUd.class);
                activitylist.add(ResimdenBulKanun.class);

            }
            intent.putExtra("ACTIVITY_LIST", activitylist);
            intent.addFlags(Intent.FLAG_ACTIVITY_NO_HISTORY);
            startActivity(intent);
            finish();
        }
        if(number ==10){
            Intent intent = new Intent(getApplicationContext(), activitylist.get(10));
            activitylist.remove(10);
            if(activitylist.size()==0){
                activitylist.add(ResimdenBulBaglama.class);
                activitylist.add(ResimdenBulBateri.class);
                activitylist.add(ResimdenBulDavul.class);
                activitylist.add(ResimdenBulDef.class);
                activitylist.add(ResimdenBulFlut.class);
                activitylist.add(ResimdenBulKeman.class);
                activitylist.add(ResimdenBulKsilafon.class);
                activitylist.add(ResimdenBulMetronom.class);
                activitylist.add(ResimdenBulObua.class);
                activitylist.add(ResimdenBulGitar.class);
                activitylist.add(ResimdenBulPiyano.class);
                activitylist.add(ResimdenBulTrombon.class);
                activitylist.add(ResimdenBulTrompet.class);
                activitylist.add(ResimdenBulZil.class);
                activitylist.add(ResimdenBulZurna.class);
                activitylist.add(ResimdenBulUd.class);
                activitylist.add(ResimdenBulKanun.class);

            }
            intent.putExtra("ACTIVITY_LIST", activitylist);
            intent.addFlags(Intent.FLAG_ACTIVITY_NO_HISTORY);
            startActivity(intent);
            finish();
        }
        if(number ==11){
            Intent intent = new Intent(getApplicationContext(), activitylist.get(11));
            activitylist.remove(11);
            if(activitylist.size()==0){
                activitylist.add(ResimdenBulBaglama.class);
                activitylist.add(ResimdenBulBateri.class);
                activitylist.add(ResimdenBulGitar.class);
                activitylist.add(ResimdenBulDavul.class);
                activitylist.add(ResimdenBulDef.class);
                activitylist.add(ResimdenBulFlut.class);
                activitylist.add(ResimdenBulKeman.class);
                activitylist.add(ResimdenBulKsilafon.class);
                activitylist.add(ResimdenBulMetronom.class);
                activitylist.add(ResimdenBulObua.class);
                activitylist.add(ResimdenBulPiyano.class);
                activitylist.add(ResimdenBulTrombon.class);
                activitylist.add(ResimdenBulTrompet.class);
                activitylist.add(ResimdenBulZil.class);
                activitylist.add(ResimdenBulZurna.class);
                activitylist.add(ResimdenBulUd.class);
                activitylist.add(ResimdenBulKanun.class);

            }
            intent.putExtra("ACTIVITY_LIST", activitylist);
            intent.addFlags(Intent.FLAG_ACTIVITY_NO_HISTORY);
            startActivity(intent);
            finish();
        }
        if(number ==12){
            Intent intent = new Intent(getApplicationContext(), activitylist.get(12));
            activitylist.remove(12);
            if(activitylist.size()==0){
                activitylist.add(ResimdenBulBaglama.class);
                activitylist.add(ResimdenBulBateri.class);
                activitylist.add(ResimdenBulGitar.class);
                activitylist.add(ResimdenBulDavul.class);
                activitylist.add(ResimdenBulDef.class);
                activitylist.add(ResimdenBulFlut.class);
                activitylist.add(ResimdenBulKeman.class);
                activitylist.add(ResimdenBulKsilafon.class);
                activitylist.add(ResimdenBulMetronom.class);
                activitylist.add(ResimdenBulObua.class);
                activitylist.add(ResimdenBulPiyano.class);
                activitylist.add(ResimdenBulTrombon.class);
                activitylist.add(ResimdenBulTrompet.class);
                activitylist.add(ResimdenBulZil.class);
                activitylist.add(ResimdenBulZurna.class);
                activitylist.add(ResimdenBulUd.class);
                activitylist.add(ResimdenBulKanun.class);

            }
            intent.putExtra("ACTIVITY_LIST", activitylist);
            intent.addFlags(Intent.FLAG_ACTIVITY_NO_HISTORY);
            startActivity(intent);
            finish();
        }
        if(number ==13){
            Intent intent = new Intent(getApplicationContext(), activitylist.get(13));
            activitylist.remove(13);
            if(activitylist.size()==0){
                activitylist.add(ResimdenBulBaglama.class);
                activitylist.add(ResimdenBulBateri.class);
                activitylist.add(ResimdenBulDavul.class);
                activitylist.add(ResimdenBulGitar.class);
                activitylist.add(ResimdenBulDef.class);
                activitylist.add(ResimdenBulFlut.class);
                activitylist.add(ResimdenBulKeman.class);
                activitylist.add(ResimdenBulKsilafon.class);
                activitylist.add(ResimdenBulMetronom.class);
                activitylist.add(ResimdenBulObua.class);
                activitylist.add(ResimdenBulPiyano.class);
                activitylist.add(ResimdenBulTrombon.class);
                activitylist.add(ResimdenBulTrompet.class);
                activitylist.add(ResimdenBulZil.class);
                activitylist.add(ResimdenBulZurna.class);
                activitylist.add(ResimdenBulUd.class);
                activitylist.add(ResimdenBulKanun.class);

            }
            intent.putExtra("ACTIVITY_LIST", activitylist);
            intent.addFlags(Intent.FLAG_ACTIVITY_NO_HISTORY);
            startActivity(intent);
            finish();
        }
        if(number ==14){
            Intent intent = new Intent(getApplicationContext(), activitylist.get(14));
            activitylist.remove(14);
            if(activitylist.size()==0){
                activitylist.add(ResimdenBulBaglama.class);
                activitylist.add(ResimdenBulBateri.class);
                activitylist.add(ResimdenBulDavul.class);
                activitylist.add(ResimdenBulGitar.class);
                activitylist.add(ResimdenBulDef.class);
                activitylist.add(ResimdenBulFlut.class);
                activitylist.add(ResimdenBulKeman.class);
                activitylist.add(ResimdenBulKsilafon.class);
                activitylist.add(ResimdenBulMetronom.class);
                activitylist.add(ResimdenBulObua.class);
                activitylist.add(ResimdenBulPiyano.class);
                activitylist.add(ResimdenBulTrombon.class);
                activitylist.add(ResimdenBulTrompet.class);
                activitylist.add(ResimdenBulZil.class);
                activitylist.add(ResimdenBulZurna.class);
                activitylist.add(ResimdenBulUd.class);
                activitylist.add(ResimdenBulKanun.class);

            }
            intent.putExtra("ACTIVITY_LIST", activitylist);
            intent.addFlags(Intent.FLAG_ACTIVITY_NO_HISTORY);
            startActivity(intent);
            finish();
        }
        if(number ==15){
            Intent intent = new Intent(getApplicationContext(), activitylist.get(15));
            activitylist.remove(15);
            if(activitylist.size()==0){
                activitylist.add(ResimdenBulBaglama.class);
                activitylist.add(ResimdenBulBateri.class);
                activitylist.add(ResimdenBulDavul.class);
                activitylist.add(ResimdenBulGitar.class);
                activitylist.add(ResimdenBulDef.class);
                activitylist.add(ResimdenBulFlut.class);
                activitylist.add(ResimdenBulKeman.class);
                activitylist.add(ResimdenBulKsilafon.class);
                activitylist.add(ResimdenBulMetronom.class);
                activitylist.add(ResimdenBulObua.class);
                activitylist.add(ResimdenBulPiyano.class);
                activitylist.add(ResimdenBulTrombon.class);
                activitylist.add(ResimdenBulTrompet.class);
                activitylist.add(ResimdenBulZil.class);
                activitylist.add(ResimdenBulZurna.class);
                activitylist.add(ResimdenBulUd.class);
                activitylist.add(ResimdenBulKanun.class);

            }
            intent.putExtra("ACTIVITY_LIST", activitylist);
            intent.addFlags(Intent.FLAG_ACTIVITY_NO_HISTORY);
            startActivity(intent);
            finish();
        }
        if(number ==16){
            Intent intent = new Intent(getApplicationContext(), activitylist.get(16));
            activitylist.remove(16);
            if(activitylist.size()==0){
                activitylist.add(ResimdenBulBaglama.class);
                activitylist.add(ResimdenBulBateri.class);
                activitylist.add(ResimdenBulDavul.class);
                activitylist.add(ResimdenBulGitar.class);
                activitylist.add(ResimdenBulDef.class);
                activitylist.add(ResimdenBulFlut.class);
                activitylist.add(ResimdenBulKeman.class);
                activitylist.add(ResimdenBulKsilafon.class);
                activitylist.add(ResimdenBulMetronom.class);
                activitylist.add(ResimdenBulObua.class);
                activitylist.add(ResimdenBulPiyano.class);
                activitylist.add(ResimdenBulTrombon.class);
                activitylist.add(ResimdenBulTrompet.class);
                activitylist.add(ResimdenBulZil.class);
                activitylist.add(ResimdenBulZurna.class);
                activitylist.add(ResimdenBulUd.class);
                activitylist.add(ResimdenBulKanun.class);

            }
            intent.putExtra("ACTIVITY_LIST", activitylist);
            intent.addFlags(Intent.FLAG_ACTIVITY_NO_HISTORY);
            startActivity(intent);
            finish();
        }

    }

    @Override
    public void onWindowFocusChanged(boolean hasFocus) {
        super.onWindowFocusChanged(hasFocus);
        if(hasFocus){
            decorView.setSystemUiVisibility(hideSystemBars());
        }
    }

    private int hideSystemBars(){
        return View.SYSTEM_UI_FLAG_LAYOUT_STABLE |
                View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY |
                View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN |
                View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION |
                View.SYSTEM_UI_FLAG_FULLSCREEN |
                View.SYSTEM_UI_FLAG_HIDE_NAVIGATION;
    }
    @Override
    protected void onPause() {
        seskes();

        super.onPause();
    }

    @Override
    protected void onStop() {
        seskes();
        super.onStop();
    }
}